// Automatically generated from DSDMS VVT templates
export const allVvtTemplates: Record<string, {
  bezeichnung: string;
  zweck: string;
  rechtsgrundlage: string;
  verantwortlicher: string;
  loeschfrist: string;
  status: string;
  dsfa: boolean;
  drittlandtransfer: boolean;
  datenkategorien: string;
  betroffenePersonen: string;
  empfaenger: string;
  tomHinweis: string;
}> = {
  "abgleich_embargolisten": {
    "bezeichnung": "Abgleich Embargolisten",
    "zweck": "Dokumentation und Protokoll des Datenabgleichs",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Altdaten nach Abgleich nach Ablauf von handels- und zollrechtlichen Aufbewahrungspflichten",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "abonnentenverwaltung": {
    "bezeichnung": "Abonnentenverwaltung",
    "zweck": "Durchführung von vertraglich vereinbarten",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "gesetzliche Vorgaben",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Name, Anschrift Vertragsdaten Lieferzeiträume Gegenstand der Lieferverpflichtung",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "administrationsservice": {
    "bezeichnung": "Administrationsservice",
    "zweck": "Durchführung aller Systemadministrationstätigkeiten",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Laufzeit der einzelnen Systemkomponenten",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Administratorendaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "ahnen_und_abstammungsforschung": {
    "bezeichnung": "Ahnen  und Abstammungsforschung",
    "zweck": "Genetische Datenbank zur Ahnen- und Abstammungsforschung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Besondere Laufzeit gem. des Vertrages Sofort, auf Antrag des Betroffenen",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "akkordlohnerfassung_elektronisch": {
    "bezeichnung": "Akkordlohnerfassung elektronisch",
    "zweck": "Arbeitsleistungsermittlung; Berechnung einer Zusatzzahlung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "nach Ablauf von steuer- und sozialversicherungspflichtigen Aufbewahrungspflichten",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Arbeitsleistungsdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "akkordlohnerfassung_manuell": {
    "bezeichnung": "Akkordlohnerfassung manuell",
    "zweck": "Arbeitsleistungsermittlung; Berechnung einer Zusatzzahlung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "nach Ablauf von steuer- und sozialversicherungsrechtlichen Aufbewahrungspflichten",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Arbeitsleistungsdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "akkreditierungsdatenbank": {
    "bezeichnung": "Akkreditierungsdatenbank",
    "zweck": "Datenbank zur Aufnahme von",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "3 Monate nach Beendigung der Veranstaltung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "angebotserstellung": {
    "bezeichnung": "Angebotserstellung",
    "zweck": "Erstellen von personalisierten Angeboten",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Gesetzliche Aufbeahrungsfristen nach HGB",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "applikationsservice": {
    "bezeichnung": "Applikationsservice",
    "zweck": "Konfiguration, Wartung und Durchführung von zentralen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Laufzeit der einzelnen Applikationen",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Administratorendaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "arbeitsplatz_sonderausstattungen": {
    "bezeichnung": "Arbeitsplatz Sonderausstattungen",
    "zweck": "Verwaltung von gesundheitsbezogenen Sonderausstattungen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Monat nach Beendigung des Arbeitsverhältnisses",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Bezeichnungen der Sonderausstattungen wie Bildschirmbrille, spezielle Bestuhlung, besondere Arbeitsplatzeinrichtung",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "arbeitszeitverwaltung_mindestlohn": {
    "bezeichnung": "Arbeitszeitverwaltung Mindestlohn",
    "zweck": "Verwaltung der nach dem Mindestlohngesetz zu führenden",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "gesetzliche Vorgaben",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Arbeitszeiten, geleistete Lohnzahlungen",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "arbeitszeitverwaltung_mindestlohn_manuell_gefuehrt": {
    "bezeichnung": "Arbeitszeitverwaltung Mindestlohn manuell gefuehrt",
    "zweck": "Verwaltung der nach dem Mindestlohngesetz zu führenden",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "gesetzliche Vorgaben",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Arbeitszeiten, geleistete Lohnzahlungen",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "archivierung_elektronischer_empfangsquittungen": {
    "bezeichnung": "Archivierung elektronischer Empfangsquittungen",
    "zweck": "Dokumentation",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "6 Monate nach Empfangsbestätigung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Lieferdatum und -zeit Adresse Unterschrift",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "archivierung_manueller_empfangsquittungen": {
    "bezeichnung": "Archivierung manueller Empfangsquittungen",
    "zweck": "Dokumentation",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "6 Monate nach Empfangsbestätigung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Lieferdatum und -zeit Adresse Unterschrift",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "aus_und_weiterbildung": {
    "bezeichnung": "Aus  und Weiterbildung",
    "zweck": "Durchführung von Mitarbeiterqualifikationen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Beendigung des Arbeitsverhältnisses",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Ausbildungs-, Lehrgangs- und Weiterbildungsmaßnahmen Qualifikationen Beurteilungen",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "auskunftsanfragen": {
    "bezeichnung": "Auskunftsanfragen",
    "zweck": "Dokumentation über Anfragen zum Datenschutz von Betroffenen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Jahr nach Beauskunftung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Name, Anschrift, Datum, Auskunftsersuchen, Beantwortung",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "ausleihverzeichnis": {
    "bezeichnung": "Ausleihverzeichnis",
    "zweck": "Verwaltung ausgeliehener Gegenstände",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Monat nach Rückgabe",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Mitgliederdatei Datum der Ausleihe / Rückgabe Gegenstand Wert",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "automatisierte_postverteilung": {
    "bezeichnung": "Automatisierte Postverteilung",
    "zweck": "Scannen der Eingangspost zur schnellen und sicheren",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Aus der Eingangsscan-Datei nach 7 Tagen",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "barkasse_manuelle_kassenabrechnung": {
    "bezeichnung": "Barkasse manuelle Kassenabrechnung",
    "zweck": "Durchführung von Bar-, Ein-und -Auszahlungen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "nach handels- und steuerrechtichen Aufbewahrungspflichten",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Datum, Betrag, Grund, Name des Betroffenen, Unterschrift",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "beirats_management": {
    "bezeichnung": "Beirats Management",
    "zweck": "Verwaltung der Beiratsmitglieder für Beratung und",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "3 Monate nach Beendigung der Beirats-Tätigkeit",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "beitragsverwaltung": {
    "bezeichnung": "Beitragsverwaltung",
    "zweck": "Vereinsfinanzierung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "10 Jahre gesetzliche Aufbewahrungsfrist",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Bankverbindung",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "besucherregistrierung": {
    "bezeichnung": "Besucherregistrierung",
    "zweck": "Besucherverwaltung, Eintritts- und Ausgangsverwaltung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Woche nach erfolgter Abmeldung (Ausgang)",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Name Firma Anschrift Eintritts- und Ausgangszeiten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "beteiligungsverwaltung": {
    "bezeichnung": "Beteiligungsverwaltung",
    "zweck": "Verwaltung von Beteiligungen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "2 Jahre nach Beendigung des Beteiligungsverhältnisses oder gem. steuerlicher Gesetzgebung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "betriebliche_altersversorgung": {
    "bezeichnung": "Betriebliche Altersversorgung",
    "zweck": "Sicherstellung einer zusätzlichen Altersversorgung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "nach Ablauf von handels- und steuerrechtlichen Ablauffristen",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Vertrags- und Leistungsdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "betriebliches_eingliederungsmanagement": {
    "bezeichnung": "Betriebliches Eingliederungsmanagement",
    "zweck": "Mitarbeiter durch spezielle Arbeitsbedingungen nach längerer",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Jahr nach erfolgter Eingliederung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Maßnahmenkatalog zur Durchführung der betrieblichen Eingliederung",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "betriebliches_vorschlagswesen": {
    "bezeichnung": "Betriebliches Vorschlagswesen",
    "zweck": "Organisations- und Produktionsverbesserungen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Jahr nach Einreichnung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Einreichung von Vorschlägen zur Verbesserung von Organi- sations- und Produktionsabläufen",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "betriebskostenabrechnung": {
    "bezeichnung": "Betriebskostenabrechnung",
    "zweck": "Ermittlung und Dokumentation der Betriebskosten",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "10 Jahre nach Jahresabschluss",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Allgemeine Betriebskosten, Immobiliendaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "betriebsratswahlen": {
    "bezeichnung": "Betriebsratswahlen",
    "zweck": "Bildung eines Wahlvorstandes",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Nach Vorgabe des BetrVG nach Durchführung der Wahlen und Ende von Einspruchsfristen",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "betriebsrenten_verwaltung": {
    "bezeichnung": "Betriebsrenten Verwaltung",
    "zweck": "Berechnungen und -verwaltungen von Betriebsrenten",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Gesetzliche Aufbewahrungsfrist",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "betriebssportverwaltung": {
    "bezeichnung": "Betriebssportverwaltung",
    "zweck": "Verwaltung der Mitglieder verschiedener Sparten des",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "nach Austritt",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Passdaten des Betriebssportverbandes",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "bewerberauswahl_manuell_gefuehrt": {
    "bezeichnung": "Bewerberauswahl manuell gefuehrt",
    "zweck": "Auswahl geeigneter Bewerber zur Einstellung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "6 Monate nach Nichteinstellung, sonst Übernahme in die Personalakte",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Bewerbungsunterlagen, Anschrift Lebenslauf, Zeugnisse, Angaben zum beruflichen Werdegang Führungszeugnis Gesundheitszeugnis",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "bewerberverfahren": {
    "bezeichnung": "Bewerberverfahren",
    "zweck": "Auswahl geeigneter Bewerber zur Einstellung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "6 Monate nach Nichteinstellung, sonst Übernahme in die Personalakte",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Bewerbungsunterlagen, Anschrift Lebenslauf, Zeugnisse, Angaben zum beruflichen Werdegang Führungszeugnis Gesundheitszeugnis",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "biometrische_zutrittskontrolle": {
    "bezeichnung": "Biometrische Zutrittskontrolle",
    "zweck": "Erhöhung der Zutrittssicherheit durch Scannen von",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Sofort nach Beendigung des Beschäftigungsverhältnisses Auf Widerruf des Betroffenen",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "blog_login": {
    "bezeichnung": "Blog Login",
    "zweck": "Angebot an Besucher / Mitglieder zur Teilnahme an",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "63 Jahre nach letztem Beitrag",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "bonitaetspruefung": {
    "bezeichnung": "Bonitaetspruefung",
    "zweck": "Kunden- und Lieferantenauskunft: Bonitätsprüfung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Jahr bei Nichtzustandekommen des Vertrages, sonst 2 Jahre sofortiger Datenaustausch bei Neubeauskunftung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Bonität allgemeine Kreditwürdigkeit Scoring",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "callcenter_gespraechsaufzeichnung": {
    "bezeichnung": "Callcenter Gespraechsaufzeichnung",
    "zweck": "Qualitätssicherung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "nach erfolgter Auswertung, spätestens nach 90 Tagen",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "ggf. Telefonnummer und Name des Anrufenden",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "casting_und_talentmanagement": {
    "bezeichnung": "Casting und Talentmanagement",
    "zweck": "Durchführung von Veranstaltungen zur Selektion von Personen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "6 Monate nach Beendigung des Vertragsverhältnis",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "cloud_anwendungen": {
    "bezeichnung": "Cloud Anwendungen",
    "zweck": "alle bisher inhouse angewendeten Office-Anwendungen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Speicherungen gemäß der gesetzlichen Aufbewahrungsfristen",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "compliance_pruefungen": {
    "bezeichnung": "Compliance Pruefungen",
    "zweck": "Planung, Steuerung und Kontrolle aller Geschäftsbereiche",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Gesetzliche Aufbeahrungsfristen nach HGB in der Regel 10 Jahre nach Beendigung des Kalenenderjahres",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "contractmanagement": {
    "bezeichnung": "Contractmanagement",
    "zweck": "Verwaltung aller für das Unternehmen abgeschlossenen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Gesetzliche Aufbewahrungsfristen",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "crm_erp_systeme": {
    "bezeichnung": "CRM ERP Systeme",
    "zweck": "Erfassung aller Kundenkontakte, Kundenkorrespondenz und",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "gesetzliche Aufbewahrungsfristen für aktive Kundenkonten, sonst 3 Jahre nach letztmaligen Kontakten",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "datenschutzschulungen": {
    "bezeichnung": "Datenschutzschulungen",
    "zweck": "Nachweis der durchgeführten Informationsveranstaltungen für",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Jahr nach Beendigung des Beschäftigungsverhältnisses",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Ort, Datum, Inhalt, ggf. Arbeitsblätter Teilnehmerlisten ggf. mit Unterschrift",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "dienstplanung": {
    "bezeichnung": "Dienstplanung",
    "zweck": "Planung für Schichtbetieb, Mitarbeitereinsatz",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Jahr nach Jahresabschluss",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Planungsdaten des zeitlichen Einsatzes",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "dienstreisenplanung": {
    "bezeichnung": "Dienstreisenplanung",
    "zweck": "Durchführung von dienstlich angeordneten Reisen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Reisekosten gem. gesetzlicher Aufbewahrungspflichten",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Reisedaten Visabeantragung",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "dokumentenmanagement": {
    "bezeichnung": "Dokumentenmanagement",
    "zweck": "Verwaltung und Archivierung aller geschäftsrelevanten",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "nach Ablauf von handels-, steuer- sozialversicherungs- rechtlichen Aufbewahrungsfristen",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "e_learning_system": {
    "bezeichnung": "E Learning System",
    "zweck": "Mitarbeiterausbildung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "3 Jahre oder 3 Monate nach Beendigung des Arbeitsverhältnisses",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Maßnahme Datum der Teilnahme Ergebnis",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "e_mail_verfahren": {
    "bezeichnung": "E Mail Verfahren",
    "zweck": "interne und externe Kommunikation",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "gesetzliche Aufbewahrunsfristen nach HGB oder 3 Jahre nach letztmaligem Kundenkontakt oder 3 Monate nach Ausscheiden eines Beschäftigten",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Kontaktdaten aller Teilnehmer des E-Mail-Verfahrens geschäftlicher E-Mail-Verkehr",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "einwilligungsdatenbank": {
    "bezeichnung": "Einwilligungsdatenbank",
    "zweck": "Dokumentation und Archivierung von Einwilligungen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "3 Monate nach Beendigung des Beschäftigungsverhältnisses oder nach Wideruf der Einwilligung",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "schriftliche Form der Einwilligungen",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "elektronische_zeiterfassung": {
    "bezeichnung": "Elektronische Zeiterfassung",
    "zweck": "Dokumentation der betrieblichen An- und Abwesenheitszeiten",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "3 Monate nach Vervollständigung der Buchungskonten 6 Monate der Korrekturbelege",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Abteilung Datum An- und Abwesenheitszeiten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "elektronischer_zahlungsverkehr": {
    "bezeichnung": "Elektronischer Zahlungsverkehr",
    "zweck": "Durchführung des elektronischen Zahlungsverkehrs",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Speicherung gem der gesetzlichen Aufbewahrungsfristen (GoBD)",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Bankverbindungs- und Zahlungsinformationen",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "ersthelferorganisation": {
    "bezeichnung": "Ersthelferorganisation",
    "zweck": "Organisation, Ausbildung und Dokumentation der Ersthelfer",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "bei jeder Veränderung der beteiligten Personen",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "externe_zahlungsabwicklung": {
    "bezeichnung": "Externe Zahlungsabwicklung",
    "zweck": "Inkassodurchführung mit externen Dienstleistern",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Gem. Vorgaben HGB",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "fahrkostenabrechnung": {
    "bezeichnung": "Fahrkostenabrechnung",
    "zweck": "Monatliche Fahrkostenzahlunge für Verträge im",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Gesetzliche Aufbewahrungsfristen nach Steuerrecht",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "fahrtenschreiberverwaltung": {
    "bezeichnung": "Fahrtenschreiberverwaltung",
    "zweck": "Steuerung des Fuhrparks",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Jahr nach Jahresabschluss nach Fahrzeugverkauf oder Stilllegung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Fahrtenschreiber",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "fahrzeug_bussgeldzahlungen": {
    "bezeichnung": "Fahrzeug Bussgeldzahlungen",
    "zweck": "Übernahme der Bußgeldzahlungen durch Verursacher",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "3 Jahre nach Verursachung oder nach Beendigung des Beschäftigtenverhältnisses",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Bußgeld, Datum, Grund, Verursacher, Fahrzeugkennzeichen",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "fahrzeugkostenabrechnung": {
    "bezeichnung": "Fahrzeugkostenabrechnung",
    "zweck": "Abrechnung der Fahrzeugkosten bei privater Nutzung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "nach Ablauf von handels- und steuerrechtlichen Aufbewahrungspflichten",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "fahrzeugverleih": {
    "bezeichnung": "Fahrzeugverleih",
    "zweck": "Vermietung von Fahrzeugen aller Art",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "gesetzliche Aufbewahrungspflichten",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Fahrzeugdaten Vertragsdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "fahrzeugverwaltung": {
    "bezeichnung": "Fahrzeugverwaltung",
    "zweck": "organisatorische und technische Verwaltung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "2 Jahre nach Jahresabschluss, Rückgabe oder Austausch des Fahrzeugs keine Aufbewahrung nach Abgabenordnung erforderlich",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Fahrer-/ Halterdaten Fahrzeugdaten Versicherungsdaten Leasing- und Abrechnungsdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "faxwerbung_elektronisch": {
    "bezeichnung": "Faxwerbung elektronisch",
    "zweck": "Werbung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "für die Dauer des Vertragsverhältnisses sofort nach Widerruf durch einen Interessenten",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "finanzbuchhaltung": {
    "bezeichnung": "Finanzbuchhaltung",
    "zweck": "finanztechnische Unternehmenssteuerung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "10 Jahre nach Jahresabschluss gemäß Abgabenordnung 8 Jahre für Buchungsbelege nach Jahresabschluss gemäß Abgabeordnung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Buchungsdaten Bilanzdaten Saldenmitteilungen, Mahnungen",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "firewalladministration": {
    "bezeichnung": "Firewalladministration",
    "zweck": "Sicherung des Unternehmensnetzwerks",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Gemäß internem Löschkonzept",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Logfiles",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "flottenmanagement": {
    "bezeichnung": "Flottenmanagement",
    "zweck": "Organisation und effektive Steuerung des Fuhrparks",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Jahr nach Fahrzeugverkauf oder Stilllegung",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Fahrzeugdaten, Fahrtwege, Fahrtzeiten, Standortdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "fotoeinwilligungen": {
    "bezeichnung": "Fotoeinwilligungen",
    "zweck": "Verwaltung der Einwilligungen zum Nachweis der",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "nach Zweckentfall",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Fotos Einwilligungen",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "fuehrerscheinkontrolle_firmenfahrzeuge": {
    "bezeichnung": "Fuehrerscheinkontrolle Firmenfahrzeuge",
    "zweck": "jährliche Führerscheinkontrolle bei Nutzungsrecht",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Jahr oder nach Durchführung der Kontrollpflichten",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "gaeste_wlan": {
    "bezeichnung": "Gaeste WLAN",
    "zweck": "gesicherter Internetzugiff für Gäste",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Monat nach Ablauf der Anmeldungszeit",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Name, Anmeldungsdatum, Verbindungszeiten, IP-Adresse",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "geburtstags_und_jubilaeumsverzeichnis": {
    "bezeichnung": "Geburtstags  und Jubilaeumsverzeichnis",
    "zweck": "soziale Verantwortung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "jährliche Neufassung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Geburtstags- und Jubiläumstermine",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "gewaehrleistung_und_garantie": {
    "bezeichnung": "Gewaehrleistung und Garantie",
    "zweck": "Aufnahme der Daten für gesetzliche Gewährleistungs-",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "6 Jahr nach Garantie- oder Gewährleistungsende",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Kaufdaten zur Registrierung gesetzlicher Gewährlesitungs- und Garantieansprüche",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "gewinnspiele": {
    "bezeichnung": "Gewinnspiele",
    "zweck": "Marketingaktionen zur Kundengewinnung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "2 Monate nach der Gewinnermittlung bei Nutzungseinwilligung bis Widerruf",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Aktionsdaten, Name der teilnehmenden Person Post- und E-Mail-Adresse, Telefon Eingangsdatum, Lösungsantwort Newsletterbestellung Einwilligung für die Datennutzung",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "handwerkerbeauftragung": {
    "bezeichnung": "Handwerkerbeauftragung",
    "zweck": "Auftragserteilung an Handwerker und Abrechnungen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "10 Jahre nach Jahresabschluss",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Auftrags- und Abrechnungsdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "hotel_zimmerverwaltung_reservierung": {
    "bezeichnung": "Hotel, Zimmerverwaltung, Reservierung",
    "zweck": "Reservierungsplanung, -durchführung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Rechnungsdaten gem. gesetzlicher Aufbewahrungsfristen Reservierungsdaten 2 Jahre",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Zeitraum der Reservierung Zahlungsdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "internetseite_mit_kontaktformular": {
    "bezeichnung": "Internetseite mit Kontaktformular",
    "zweck": "externe Datenerfassung durch Eingabe in ein Kontaktformular",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Allgemeines 6 Monate oder gesetzliche Aufbewahrungsfristen nach HGB",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Kontaktdaten Einwilligungen Informationen zu Maßnahmen, Aufträgen, Korrespondenz sonstige Nachrichten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "it_support_extern": {
    "bezeichnung": "IT Support extern",
    "zweck": "Wiederherstellen eines laufenden IT-Betriebs",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "sofort nach Beendigung der Dienstleistung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Name Nutzerkennung",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "kautionsverwaltung": {
    "bezeichnung": "Kautionsverwaltung",
    "zweck": "Verwaltung hinterlegter Kautionen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "10 Jahre nach Jahresabschluss",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Kautionsdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "kfz_auswerten_von_fahrzeugdaten": {
    "bezeichnung": "Kfz Auswerten von Fahrzeugdaten",
    "zweck": "Serviceplanung, Fehlersuche, Reparaturdurchführung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "vor Verkauf oder Verschrottung",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "kostenstellen_kostentraegerabrechnung": {
    "bezeichnung": "Kostenstellen , Kostentraegerabrechnung",
    "zweck": "Übersicht über Kostenentwicklungen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "6 Jahre",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "kundendatenerfassung": {
    "bezeichnung": "Kundendatenerfassung",
    "zweck": "Erhebung von Kundendaten über das Web-Portal",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "6 Jahre nach Jahresbschluss Korrepondenz gemäß HGB Bei Finanzdaten entsprechend der gesetzlichen Aufbewahrungsfristen",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "kundendienst_und_service": {
    "bezeichnung": "Kundendienst und  service",
    "zweck": "Reklamations- und Kundendienstbearbeitung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "je nach Ereignis Garantiezeit sonstige Anfrage 6 Monate",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Anfragegrund Maßnahme",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "kundenkarten_verwaltung": {
    "bezeichnung": "Kundenkarten Verwaltung",
    "zweck": "Verwaltung von Kundenkarten",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "sofort bei Abmeldung durch den Kundenkarteninhaber",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "kundenzufriedenheitsumfragen": {
    "bezeichnung": "Kundenzufriedenheitsumfragen",
    "zweck": "Kundenbetreuung, Verbesserungsanalysen für alle angebotenen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Gemäß internem Löschkonzept",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "kurzarbeit_verwaltung": {
    "bezeichnung": "Kurzarbeit Verwaltung",
    "zweck": "Durchführung von Kurzarbeitszeiten gem. Zusammenarbeit",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Gesetzliche Aufbewahrungsfrist",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "lernplattform_dozentenpool": {
    "bezeichnung": "Lernplattform Dozentenpool",
    "zweck": "Dozenten-Verwaltung mit Lerninhalten, Methoden",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Jahr nach Beendigung der Zusammenarbeit",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "lizenzmanagement": {
    "bezeichnung": "Lizenzmanagement",
    "zweck": "Verwaltung aller für das Unternehmen abgeschlossenen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "3 Monate nach Beendigung einer Lizenznutzungsberechtigung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "mahn_und_vollstreckungswesen": {
    "bezeichnung": "Mahn  und Vollstreckungswesen",
    "zweck": "Sicherstellung der Zahlungsleistung von Schuldnern",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Gesetzliche Aufbewahrungsfristen nach HGB",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "mautgebuehrenverwaltung": {
    "bezeichnung": "Mautgebuehrenverwaltung",
    "zweck": "gesetzliche Dokumentation der Mautgebühren",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "6 Jahre nach Jahresabschluss",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Fahrzeugdaten Fahrtenstrecke Datum Gebühren",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "messengerdienste": {
    "bezeichnung": "Messengerdienste",
    "zweck": "Durchführung interner und externer Kommunikation",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "6 Monate",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "messestandverwaltung": {
    "bezeichnung": "Messestandverwaltung",
    "zweck": "Datenaufnahme Besucher am Messestand",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Jahr nach Messedurchführung oder nach Widerruf der Datennutzung des Betroffenen",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "mietabrechnungen": {
    "bezeichnung": "Mietabrechnungen",
    "zweck": "Verwaltung der Mietverträge und Einzug der Mieten",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "10 Jahre",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "mitarbeiterbefragung": {
    "bezeichnung": "Mitarbeiterbefragung",
    "zweck": "Rrgebnisorientierte Motivation und Zufriedenheit",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Umfrageformulare sofort nach Abschluss der Umfrage und der Ergebnisermittlung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "mitgliederverwaltung": {
    "bezeichnung": "Mitgliederverwaltung",
    "zweck": "Durchführung der satzungsgemäßen Vereinsführung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "steuerliche Daten gem. gesetzlicher Vorgaben sonstige Mitgliederdaten 1 Jahr nach Austritt",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Name, Anschrift Eintrittsdatum, Geburtsdatum Spartenmitgliedschaft, Beiträge Einwilligung bei E-Mail-Nutzung",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "mobile_device_management": {
    "bezeichnung": "Mobile Device Management",
    "zweck": "Verwaltung der mobilen IT-Geräte",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "bei Rückgabe des Gerätes Ersatzbestellung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Geräte-Systemdaten Telefonnummer installierte Applikationen (Apps)",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "nachlassverwaltung": {
    "bezeichnung": "Nachlassverwaltung",
    "zweck": "Verwaltungen von Erbnachlass für Erben,-gemeinschaften",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Gem. gesetzlicher Aufbewahrungsfristen",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "newsletter_empfaenger_analyse": {
    "bezeichnung": "Newsletter Empfaenger Analyse",
    "zweck": "Versand von E-Mails und Auswertung der Effektivität des",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "nach 12 Monaten, Löschung des Personenbezuges anonymisieren",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "E-Mail-Adresse, Versanddatum, Anrede, Name, Analysedaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "newsletterversand": {
    "bezeichnung": "Newsletterversand",
    "zweck": "Versand von Informationen mittels Newsletter",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "sofort nach Widerruf durch den Besteller",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Einwilligung des Bestellers (Opt-Out / Opt-In) Quelle, Datum und Anlass der Bestellung",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "notfallsituationenplan": {
    "bezeichnung": "Notfallsituationenplan",
    "zweck": "Aktionsplan zum schnellen Eingreifen bei definierten",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "jährliche Überarbeitung Änderungen des Risikos Wechsel von betroffenen Firmen oder Personen",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "in den Ablauf einzubeziehende Personen Telefonnummer",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "office_anwendungen": {
    "bezeichnung": "Office Anwendungen",
    "zweck": "Office-Anwendungen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Speicherungen gemäß der gesetzlichen Aufbewahrungsfristen",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "online_coaching": {
    "bezeichnung": "Online Coaching",
    "zweck": "Coaching im Rahmen von Onlinemeetings mit Gesprächs-",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "3 Jahre nach Coachingende",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Gesprächsnotizen",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "parkhaus_dauerreservierungen": {
    "bezeichnung": "Parkhaus Dauerreservierungen",
    "zweck": "Verwaltungg und Abrechnung belegter Parkplätze",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "3 Monate nach Beendigung des Mietverhältnisses Finanzdaten gem. gesetzlicher Aufbewahrungsfristen",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "parkplatzverwaltung": {
    "bezeichnung": "Parkplatzverwaltung",
    "zweck": "Zuordnung der betrieblichen Parkplätze",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Monat nach Entfall der Parkberechtigung",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "passwortverwaltung": {
    "bezeichnung": "Passwortverwaltung",
    "zweck": "zentrale Verwaltung der Passwörter,",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Löschen 3 Monate nach Beendigung der Zugriffsberechtigung Sperren sofort nach Beendigung der Zugriffsberechtigung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "patientendaten_zur_abrechnung": {
    "bezeichnung": "Patientendaten zur Abrechnung",
    "zweck": "Abrechnung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Nach Ablauf gesetzlicher Aufbewahrungsfristen",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "persoenliches_coaching": {
    "bezeichnung": "Persoenliches Coaching",
    "zweck": "Individuelle Beratung einer Person in persönlichen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "3 Jahre nach Coachingende",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Gesprächsnotizen",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "personalabrechnungssystem": {
    "bezeichnung": "Personalabrechnungssystem",
    "zweck": "Durchführung der Lohn- und Gehaltsabrechnung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "10 Jahre nach Jahresabschluss gem. Abgabenordnung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten Finanzdaten Arbeitszeitdaten Sozialversicherungsdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "personalakte_manuell_gefuehrt": {
    "bezeichnung": "Personalakte manuell gefuehrt",
    "zweck": "Dokumentation der Arbeitsvertragsdaten",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "3 Jahre nach Beendigung des Arbeitsverhältnisses",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Personalstammdaten Lohnsteuerdaten, Sozialversicherungsausweis Krankmeldungen Befähigungsnachweise, Abmahnungen Veränderungen persönlicher Verhältnisse",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "personaldaten_externer_mitarbeiter": {
    "bezeichnung": "Personaldaten externer Mitarbeiter",
    "zweck": "Verwaltung der Personaldaten externer Mitarbeiter",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "3 Jahre nach Beendigung des Beschäftigungsverhältnisses oder nach Ablauf handels- und steuerrechtlicher Aufbewahrungspflichten",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "personaldatenverwaltung": {
    "bezeichnung": "Personaldatenverwaltung",
    "zweck": "Dokumentation der Arbeitsvertragsdaten",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "3 Jahre nach Beendigung des Arbeitsverhältnisses",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Personalstammdaten Lohnsteuerdaten, Sozialversicherungsausweis Krankmeldungen Befähigungsnachweise, Abmahnungen Veränderungen persönlicher Verhältnisse",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "personalverkauf": {
    "bezeichnung": "Personalverkauf",
    "zweck": "Verbilligter Einkauf für Mitarbeiter",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Gesetzliche Aufbewahrungsfristen für Finanzbuchhaltung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Umsatz- und Abrechnungsdaten Rechnungserstellung Lieferscheinerstellung",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "pfaendungen_und_abtretungen": {
    "bezeichnung": "Pfaendungen und Abtretungen",
    "zweck": "Verwaltung von betrieblichen Forderungen oder Forderungen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Gem. gesetzlicher Aufbewahrungsfristen",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "projektdatenbank": {
    "bezeichnung": "Projektdatenbank",
    "zweck": "Projektabwicklung, Erfassung der Projektfolgen und Projekt-",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Jahr nach Projektabschluss",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "raumbuchung": {
    "bezeichnung": "Raumbuchung",
    "zweck": "Planung der Nutzung von Meetingräumen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "6 Monate nach Ablauf der Nutzung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "reisekostenabrechnung": {
    "bezeichnung": "Reisekostenabrechnung",
    "zweck": "Abrechnung für dienstlich angeordnete Reisetätigkeiten",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "8 Jahre gemäß Abgabenordnung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Fahrt- und Übernachtungskosten Spesen Bewirtungskosten sonstige Auslagen Kostenaufstellungen",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "reparaturauftraege": {
    "bezeichnung": "Reparaturauftraege",
    "zweck": "Durchführung kostenpflichtiger Reparaturen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "2 Jahre nach Reparaturdurchführung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Kostenvoranschläge, Warendaten, Reparaturaufträge",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "restaurant_reservierungen": {
    "bezeichnung": "Restaurant Reservierungen",
    "zweck": "Platz- und Tischreservierungen,",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Nach Beendigung der Inanspruchnahme durch den Kunden",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "rezensionen": {
    "bezeichnung": "Rezensionen",
    "zweck": "Erfassung und Wiedergabe von Kundenbeurteilungen über Waren",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "So lange die Ware oder die Dienstleistung angeboten wird",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Beurteilung von Waren",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "robinsonliste": {
    "bezeichnung": "Robinsonliste",
    "zweck": "Datenbank für Adressdaten, E-Maildaten, Telefondaten etc.",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Keine festgelegten Löschfristen Hinweis für Löschhfristen sollten in den AGB und/oder in den Datenschutzinformationen aufgenommen werden",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "schluesselverwaltung": {
    "bezeichnung": "Schluesselverwaltung",
    "zweck": "Dokumentation der Schlüsselverwaltung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Nutzerdaten 3 Monate nach Rückgabe",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Schlüsselnutzer Aus- und Rückgabedaten Schlüsselart",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "schutz_und_arbeitskleidung": {
    "bezeichnung": "Schutz  und Arbeitskleidung",
    "zweck": "Nachweis Aus- und Rückgabe von Arbeitsbekleidungen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "12 Monate nach Rückgabe",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Art, Größe, Datum der Ausgabe und Rückgabe",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "sicherheitsbeauftragtenorganisation": {
    "bezeichnung": "Sicherheitsbeauftragtenorganisation",
    "zweck": "Organisation, Ausbildung und Dokumentation",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "bei jeder Veränderung der beteiligten Personen",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "skill_datenbank": {
    "bezeichnung": "Skill Datenbank",
    "zweck": "Personal-Karriere-Förderung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Überarbeitung alle 2 Jahre Löschung innerhalb eines Jahres nach Beendigung des Arbeitsverhältnisses",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Angaben zu speziellen Arbeitsfähigkeiten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "sonderzahlungen": {
    "bezeichnung": "Sonderzahlungen",
    "zweck": "Bonuszahlungen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "steuerliche Daten gem. Aufbewahrungsfristen sonstige Daten nach Ausscheiden des/der Begünstigten",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Mitarbeiterbeurteilungen jährliche Zielvereinbarungen",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "speditionsabwicklung": {
    "bezeichnung": "Speditionsabwicklung",
    "zweck": "Abwicklung von Speditionsaufträgen, Transportabwicklungen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "gem. der gesetzlichen Aufbewahrungsfristen; HGB",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Auftragsdaten, Lieferdaten Empfängerinformationen, Adressen, Telefon",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "spiel_und_wettkampfergebnisse": {
    "bezeichnung": "Spiel  und Wettkampfergebnisse",
    "zweck": "Veröffentlichung von Spiel-/Wettkampfergebnissen im Internet",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "2 Jahre der Einzelergebnisse besondere Ergebnisstatistiken ohne Zeitbegrenzung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Name, ggf. Alter, Sparte, allgemeine Wettkampfdaten Ergebnisveröffentlichungen",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "sponsorenverwaltung": {
    "bezeichnung": "Sponsorenverwaltung",
    "zweck": "Verwaltung bestehender Sponsoren mit Leistungsdaten",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Gemäß stuergesetzlicher Aufbewahrungsfristen",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "telefondatenbank": {
    "bezeichnung": "Telefondatenbank",
    "zweck": "interne und externe telefonische Kommunikation",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Monat nach Ausscheiden des/der Beschäftigten",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Abteilung Funktion, Tätigkeit Telefonnummer ggf. Bild ggf. E-Mail-Adresse",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "telefonkostenabrechnung": {
    "bezeichnung": "Telefonkostenabrechnung",
    "zweck": "Aufzeichnung der Telefonkosten; ggf. mit Zahlungsanforderung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "nach Ablauf von handels- u. steuerrechtlichen Aufbewahrungspflichten",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "terminverwaltungssystem": {
    "bezeichnung": "Terminverwaltungssystem",
    "zweck": "Personalsteuerungen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "2 Monate nach Ereignisbeendigung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Anlass, Teilnehmer Abteilung, Firma Zeitangaben",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "tracking_und_auslieferung_von_paketen": {
    "bezeichnung": "Tracking und Auslieferung von Paketen",
    "zweck": "Durchführung und Dokumentation der Paketzustellung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "gesetzliche Aufbewahrungsfristen gem HGB",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Ablieferungsnachweis, manuelle oder elektronische Unterschrift",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "trainings_und_wettkampfplanung": {
    "bezeichnung": "Trainings  und Wettkampfplanung",
    "zweck": "Mitgliederbetreuung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Jahr nach Saisonablauf",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Mitgliederdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "urlaubsplanung": {
    "bezeichnung": "Urlaubsplanung",
    "zweck": "Unternehmensplanung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "2 Jahre; aktuell laufendes und vergangenes Geschäftsjahr",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Anspruchstage, Name, Abteilung, Abwesenheitszeit",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "verarbeitung_von_patientendaten_zur_behandlung": {
    "bezeichnung": "Verarbeitung von Patientendaten zur Behandlung",
    "zweck": "Behandlungsdokumentation",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Nach Ablauf gesetzlicher Aufbewahrungsfristen",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "versicherungsmanagement": {
    "bezeichnung": "Versicherungsmanagement",
    "zweck": "Schadensregulierung firmeneigener und externer Ansprüche",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "gesetzliche Aufbewahrungspflichten",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Versicherungsereignis Anspruchsteller Anspruchshöhe Vergleichsangebote",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "vertriebs_umsatz_und_leistungsdaten": {
    "bezeichnung": "Vertriebs , Umsatz  und Leistungsdaten",
    "zweck": "Umsatz- und Gratifikationsfeststellung, Vertriebssteuerung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "3 Jahre nach Jahresabschluss 1 Jahr nach Beendigung des Beschäftigtenverhältnisses",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "videoueberwachung": {
    "bezeichnung": "Videoueberwachung",
    "zweck": "Schutz vor Vandalismus; Geschäftsgelände und -gebäude",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "7 Tage",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Videoaufzeichnungen von Fahrzeugen und Personen",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "videoueberwachung_im_warenlager": {
    "bezeichnung": "Videoueberwachung im Warenlager",
    "zweck": "Aufzeichnungen der Warenbewegungen im Umschlagslager zum",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Archivierung gem. § 439 HGB 1 Jahr nach An- oder Ablieferung zur Sicherstellung von Rechtsansprüchen",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Videoaufzeichnungen der Warenbewegungen",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "warenruckruef_und_reparaturservice": {
    "bezeichnung": "Warenruckruef  und Reparaturservice",
    "zweck": "Kundenorientierte Diesnstleistung zur Schadensbehebung",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Nach Gewährleistungsablauf",
    "status": "aktiv",
    "dsfa": false,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "webtracking": {
    "bezeichnung": "Webtracking",
    "zweck": "Erfassung der Besucherströme zur Optimierung der",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Anonymisierung nach Erhebung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "IP-Adresse, techn. Browserinformation, Gerät, Provider, Standort, Interessen, besuchte Seiten; bei demoskopischen Auswertungen: Alter, Familienstatus, Geschlecht, finanzieller Status",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "werbesperrliste": {
    "bezeichnung": "Werbesperrliste",
    "zweck": "Sperren von Adressdaten nach Widerruf der Betroffenen",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "alte Daten nach erneuter Aufnahme durch Einwilligung des Absenders löschen",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "postalische Adressdaten, E-Mail-Adresse und Telefonnummer",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "zentrale_druckerstellung": {
    "bezeichnung": "Zentrale Druckerstellung",
    "zweck": "Zentrale Druckerstellung von Dokumenten",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "Login-Informationen nach Beendigung der Zugangsberichtigung Dokumentenspeicher sofort nach Druckerstellung",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Stammdaten, Kontaktdaten",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "zutrittskontrolle_manuelle_protokollfuehrung": {
    "bezeichnung": "Zutrittskontrolle manuelle Protokollfuehrung",
    "zweck": "Zutrittsnachweis für gesondert gesicherte Räume ohne",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Monat",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Protokolldateien Eingangs- und Ausgangszeiten ggf. Anlass",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  },
  "zutrittskontrollsystem": {
    "bezeichnung": "Zutrittskontrollsystem",
    "zweck": "Sicherung Firmenglände,",
    "rechtsgrundlage": "Art. 6 Abs. 1 lit. b (Vertrag) & § 26 BDSG",
    "verantwortlicher": "Fachabteilung / Team",
    "loeschfrist": "1 Monat",
    "status": "aktiv",
    "dsfa": true,
    "drittlandtransfer": false,
    "datenkategorien": "Protokolldateien Eingangs- und Ausgangszeiten ggf. Anlass",
    "betroffenePersonen": "Beschäftigte, Kunden, Partner",
    "empfaenger": "Interne Fachabteilungen",
    "tomHinweis": "Siehe TOM-Richtlinie des Unternehmens (BSI IT-Grundschutz)"
  }
};
